Add min/max levels to TOC, make links in TOC optional
mzlogin/vim-markdown-toc pull request #58
Opened 2019-03-21 19:41 UTC by ndaman

Defined three new global variables to govern new options

g:vmt_link is boolean, when true (default) the TOC generates links as before, when false only the header is listed in the toc with no link

g:vmt_min_level and g:vmt_max_level define the minimum and maximum header levels to display in the toc. If you have subheadings that you do not wish displayed in the TOC you can set these options accordingly.

2021-01-31 10:59 UTC, langer-jaros commented
Hi @mzlogin and @ndaman, can I ask you what is the status of this request?
I may have missed something, I see the project is active yet I did not found any comment about this feature. Thanks for your response.

2021-01-31 17:26 UTC, ndaman commented
I don't think this PR was ever merged, so I made my own fork with it implemented (it was a very small change).

2021-02-18 21:08 UTC, langer-jaros commented
That is pitty, anyway thanks for the reply, I will probably use your solution as soon as I will need it again.

2021-02-19 01:15 UTC, mzlogin commented
@ndaman @langer-jaros I'm sorry I didn't process this Pull Request in time. I'll review it now.

2021-02-19 01:21 UTC, mzlogin requested changes

2021-02-19 01:21 UTC, mzlogin commented on ftplugin/markdown.vim
> +    let g:vmt_max_level = 3
I think default value of `g:vmt_max_level` is 6 better, otherwise it will change the default behavior of the plugin.

2021-02-19 01:21 UTC, mzlogin commented on ftplugin/markdown.vim
> +       		 	let l:heading = l:heading . l:listItemChar
The indentation of this line needs to be optimized.

2021-03-02 07:39 UTC, merged

2021-03-02 07:55 UTC, mzlogin commented
Merged, thx! @ndaman @langer-jaros